keys:
  - &user_vera age1w7xthmy2u80yp9jx98dnmcek0xcdcfmjx5at823m3536rkp5q3xqkqfw2j
  - &user_neith age10h2dan2d3jgy8tjq4djhu5lg4krx2m735nxcvg2schkpkvht0ynsmpdqne
  - &host_miraclecrusher age1hl9999dlv29qejtac0sdw7nnm9d06uh4nzmgc029ndg40vllavyq5u0pqu
  - &host_neithdeck age1uj0nmmvdeajg0hqlahe839c5r4n6nz0r6ampcwa46yhetx32kgrqqky22x
  - &host_veradeck age1kvsa0ka66tzx3qdq6cacehyyfg80ecq6jfgqxgf8098mdah4earspnft40
  - &host_asiyah null
  - &host_briah age1mlznec0ruk9xgkzygpmetsfvutxk4qml636rqcvzpzudyp4wlcfqzgh2e2
creation_rules:

  - path_regex: 'users/vera/secrets/*'
    key_groups:
    - age:
      - *user_vera
      
  - path_regex: 'users/neith/secrets/*'
    key_groups:
    - age:
      - *user_neith
      - *user_vera

  - path_regex: 'hosts/miracle-crusher/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_miraclecrusher

  - path_regex: 'hosts/vera-deck/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_veradeck

  - path_regex: 'hosts/neith-deck/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *user_neith
      - *host_neithdeck

  - path_regex: 'hosts/asiyah/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_asiyah

  - path_regex: 'hosts/briah/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_briah